version: '3.8'

services:
  app:
    build: .
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - MONGO_URI=mongodb://localhost:27017/mydb
      - JWT_SECRET=R2kSUWXmK9rU28EhYxirY0DZ40RTr5ju0ppH7bkCSwXmALwoHh
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
